services:
  personal_website_flask:
    container_name: personal_website_flask
    user: "$DOCKER_USER_STR"
    ports:
      - "8080:8080"                                         # SYNC: Nginx and entrypoint Gunicorn ports
    build:
      context: ../../                                       # must be parent; Dockerfile can't access parent dirs
      dockerfile: deployment/docker/flask/Dockerfile        # SYNC: path, relative to `context`
      network: host
    env_file:                                               # SYNC: env file paths
      - ./flask/.env
      - ./flask/.flaskenv
    volumes:
      - type: bind                                          # for persisting uploaded images in static folders
        source: ../../app/blog/static/blogpage/             # SYNC: path
        target: /personal_website/app/blog/static/blogpage/ # SYNC: path, Dockerfile WORKDIR
    restart: always
  personal_website_mysql:
    container_name: personal_website_mysql
    user: "$DOCKER_USER_NAME"
    ports:
      - "3306:3306"
      - "33060:33060"
    image: "mysql:8.0.37"                                   # SYNC: host's MySQL version if using bind mount
    volumes:
      - type: bind                                          # for persisting database
        source: ./mysql/mysql_data_dir/                     # SYNC: MySql data directory for persistence
        target: /var/lib/mysql/
    restart: always
