services:
  personal_website_flask:
    container_name: personal_website_flask
    user: "$DOCKER_USER_STR"
    ports:
      # SYNC: Nginx and entrypoint Gunicorn ports
      - "8080:8080"
    build:
      # must be parent; Dockerfile can't access parent dirs
      context: ../../
      # SYNC: path, relative to `context`
      dockerfile: deployment/docker/flask/Dockerfile
      network: host
    # SYNC: env file paths
    env_file:
      - ./flask/.env
      - ./flask/.flaskenv
    volumes:
      # for persisting uploaded images in static folders
      - type: bind
        # SYNC: path
        source: ../../app/blog/static/blogpage/
        # SYNC: path, Dockerfile WORKDIR
        target: /personal_website/app/blog/static/blogpage/
    restart: unless-stopped
  personal_website_mysql:
    container_name: personal_website_mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    user: "$DOCKER_USER_STR"
    ports:
      - "3306:3306"
      - "33060:33060"
    # SYNC: host's MySQL version if using bind mount
    image: "mysql:8.0.37"
    volumes:
      # for persisting database
      - type: bind
        # SYNC: MySql data directory for persistence
        source: ./mysql/mysql_data_dir/
        target: /var/lib/mysql/
    restart: unless-stopped
