name: Check Markdown links
on: push
permissions:
  contents: read

jobs:
  check-markdown-links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: umbrelladocs/action-linkspector@v1
      with:
        config_file: .linkspector.yml
